name: frontend

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 12345:3000
    volumes:
      - /usr/app/node_modules
      - .:/usr/app

  node-server-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
